### PR TITLE
MiSTer: append `games/` to every mister cifs rom folder

### PR DESCRIPTION
**Pull request by birdybro**
As per @theypsilon's comments here https://github.com/danmons/retronas/issues/21#issuecomment-1029052031 (which are totally accurate), best practices would be to append `games/` to the beginning of each destination folder for the layout. This proposed change ought to fix it (please double check my work, I've never done anything in Ansible before).

The core path hierarchy works like so:

https://birdybro.github.io/MkDocs_MiSTer/cores/paths/#path-priority

### CODE REVIEW

**Comment by sairuk** [comment]
This could have been achieved with appending `games` to `dest:` in a single spot could it not removing a lot of duplication?

` dest: "{{ retronas_path }}/mister/games/{{ item.dest }}"`

also while we are at it, couldn't we move `../roms/` up to `src:` and remove some additional duplication?

`src: "../roms/{{ item.src }}"`

Another note on the existing approach, not specifically related to these changes. I would have always thought it better to use absolute pathing instead of relative because it is clearer/cleaner, there should be a var than can be used in `src:`

**Comment by birdybro** [comment]
That would cause problems if at a later time there might be a need or want to create things like `/saves/` or `/wallpapers/` in the root of the share. I was trying to leave that possibility open, however there is probably a better way by creating another variable in the yaml for games, but that would require a lot of additional redundancy for each of these lines too, I suspect.

**Comment by sairuk** [comment]
The way i did this in puppet many years ago was to have a single array for the folders with src/dest that existed globally for the manifest I then have 3 loops over that array that inject the unique paths i.e. roms, saves, config etc within the loop, it shouldn't need to be any different with ansible.

In regards to saves, (going the opposite way perhaps) I had a setup that would leverage systemd path files to monitor the save paths for changes and then the sync was handled by a git commit and push in a systemd service unit .. kinda daft being binary files but I got sick of restarting Chrono Trigger. These systemd path units also leveraged the same array to generate the instances.

**Comment by sairuk** [comment]
We'll hold off on this one until we've had a bit more of a discussion around the apprach and the new concepts you've proposed in discussion https://github.com/danmons/retronas/discussions/60. 

I've created an alt branch to test ideas out. If you could take a look at the approach in the [fix-mister-shares-alt](https://github.com/danmons/retronas/tree/fix-mister-paths-alt) branch it may help demonstrate my approach.

**Comment by sairuk** [comment]
Thanks for the submission but we're going to close this one off and approach it as per https://github.com/danmons/retronas/pull/86 which should better accommodate the future sync and share vision you have proposed.

**Pull request closed without merging**
