### PR TITLE
- add correction for the concatenation in path_list

### PR DESCRIPTION
**Pull request by RMZK**
- add correction for the concatenation in path_list
- add a when condition to ensure the correct conditions are met when constructing the link_list.

### CODE REVIEW

**Comment by RMZK** [comment]
I was having trouble to create the generic rom folders due to the way the concatenation was done. This fixed the issue on Debian 11.2, 11.7 and 12

**Comment by tjanas** [comment]
I also experienced concatenation issues on Debian 12.

**Comment by sairuk** [comment]
This needs to be rebased against the testing branch, we don't accept pulls into main

**Comment by RMZK** [comment]
> This needs to be rebased against the testing branch, we don't accept pulls into main

Sorry I did not know, let me redo the PR. Also the Mister CIFS script has the same issue so I'm going to change it too.

**Pull request closed without merging**
